export * from './Login'
export * from './Signup'
export * from './Home'
export * from './NewspaperRender'
export * from './ManageUsers'
export * from './ChangePassword'
export * from './ChangeUsername'
export * from './ManageNewspaper'
